# how to import dataset in pythoon using pandas library file
written by dr. ammar toufail 

date: 7.12.2024  

email: ....

In [ ]:
pip install pandas

In [10]:
import pandas as pd

In [17]:
df = pd.read_excel("pandas_01_day6.xlsx")

In [18]:
df

    Height  Weight Favourite Dish
0      5.8     101  Chicken Pulao
1      6.2      92        Biryani
2      5.9      62  Karahi Ghosht
3      5.9      95  Chicken Pulao
4      5.9      55  Chicken Pulao
..     ...     ...            ...
82     5.4      55          Pasta
83     5.9      73  Karahi Ghosht
84     5.4      61        Biryani
85     6.2      68  Chicken Pulao
86     5.1      96        Biryani

[87 rows x 3 columns]

In [19]:
df.head()

   Height  Weight Favourite Dish
0     5.8     101  Chicken Pulao
1     6.2      92        Biryani
2     5.9      62  Karahi Ghosht
3     5.9      95  Chicken Pulao
4     5.9      55  Chicken Pulao

In [20]:
df.index

RangeIndex(start=0, stop=87, step=1)

In [22]:
df.columns

Index(['Height', 'Weight', 'Favourite Dish'], dtype='object')

In [26]:
df.describe()

          Height      Weight
count  87.000000   87.000000
mean    5.499425   70.436782
std     0.787626   16.748968
min     0.700000   25.000000
25%     5.200000   60.000000
50%     5.600000   70.000000
75%     5.850000   80.000000
max     8.000000  125.000000

In [27]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,77,78,79,80,81,82,83,84,85,86
Height,5.8,6.2,5.9,5.9,5.9,5.3,5.6,5.9,5.1,5.4,...,5.5,5.3,5.3,5.4,5.5,5.4,5.9,5.4,6.2,5.1
Weight,101,92,62,95,55,59,50,76,78,68,...,85,72,62,55,52,55,73,61,68,96
Favourite Dish,Chicken Pulao,Biryani,Karahi Ghosht,Chicken Pulao,Chicken Pulao,Biryani,Pasta,Biryani,Biryani,Biryani,...,Biryani,Karahi Ghosht,Biryani,Pasta,Karahi Ghosht,Pasta,Karahi Ghosht,Biryani,Chicken Pulao,Biryani